:json = Content-Type: application/json
:url = http://localhost:8888

###

GET :url/snap/2
:json

###

POST :url/snap/create
:json

{"snap/id": 2,
 "snap/user_id": 1,
 "snap/name": "just a comment",
 "snap/content": "(comment)",
 "snap/language_id": 1}

###

POST :url/create-snap
:json

{"snap/id": 2,
 "snap/name": "IT'S JUST A COMMENT, OKAY?"}

###

DELETE :url/vollcheck/5
:json

###
