:json = Content-Type: application/json
:url = http://localhost:8888
:token = Token eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyL2lkIjoxLCJ1c2VyL3VzZXJuYW1lIjoidm9sbGNoZWNrIn0.w92A7hyp4SbpsyVqRwUkqdmGmkCbSu9BdjNZ1arOH1Y
:auth = authorization: :token

###

GET :url/snap/1
:json

###

GET :url/user/vollcheck
:json

### snap create

POST :url/snap/
:json

{"snap/user_id": 1,
 "snap/name": "just a comment another one",
 "snap/content": "(commentfdajslfdsajlfdajslf)",
 "snap/language_id": 1}

###

# snap update, not create

POST :url/snap/
:json

{"snap/id": 2,
 "snap/name": "IT'S JUST A COMMENT, OKAY?"}

###

DELETE :url/snap/6
:json

###

GET :url/
:json

###

GET :url/snaps
:json
:auth

###

GET :url/me
:json
:auth

###

POST :url/login
:json

{"username": "vollcheck",
 "password": "admin"}

###

POST :url/register
:json

{"username": "another",
 "password": "admin",
 "email": "another@one.com",
 "bio": "something something",
 "avatar": ""}

###

# {
#   "status": 200,
#   "body": {
#     "user": {
#       "user/id": 1,
#       "user/username": "vollcheck"
#     },
#     "token": "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyL2lkIjoxLCJ1c2VyL3VzZXJuYW1lIjoidm9sbGNoZWNrIn0.w92A7hyp4SbpsyVqRwUkqdmGmkCbSu9BdjNZ1arOH1Y"
#   }
# }
